---
repos:
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.25.0
      hooks:
          - id: yamllint
    - repo: https://gitlab.com/pycqa/flake8
      # flake8 version should match .travis.yml
      rev: 3.8.4
      hooks:
          - id: flake8
