dist: trusty
language: python
python:
- '3.6'
sudo: true
cache:
    apt: true
    pip: true
addons:
  apt:
    packages:
    - gdal-bin
    - gfortran
    - libatlas-base-dev
    - libatlas-dev
    - libgdal1-dev
    - liblapack-dev
    - libproj-dev
install:
- mkdir pdstools
- pushd pdstools
- travis_retry wget https://raw.githubusercontent.com/GeoscienceAustralia/pds-tools/988b0b6e8495f9224c384ec0ac4c720c054d022c/pdsinfo.c
- clang -O pdsinfo.c -lm -o pdsinfo
- export PATH="$(pwd):${PATH}"
- popd
- export CPLUS_INCLUDE_PATH="/usr/include/gdal"
- export C_INCLUDE_PATH="/usr/include/gdal"
  # The python gdal bindings version need to match the gdal version of the system
- travis_retry pip install --upgrade pytest pytest-cov pycodestyle flake8 coveralls GDAL==1.10.0 rasterio[s3]
- travis_retry pip install -e .[test]
  # Either both set or none. See: https://github.com/mapbox/rasterio/issues/1494
- [ -z ${AWS_SECRET_ACCESS_KEY+x} ] && unset AWS_ACCESS_KEY_ID;

script:
- ./check-code.sh --runslow
after_success: coveralls

before_deploy:
- pip install s3pypi

deploy:
-  provider: script
   script: s3pypi --bucket datacube-core-deployment
   on:
     all_branches: true  # Let the condition below decide if the branch is to be deployed
     condition: $TRAVIS_BRANCH = "develop" || ! -z "${TRAVIS_TAG}"  # develop branch or tags
     repo: GeoscienceAustralia/eo-datasets  # Don't attempt to deploy from forks

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
        secure: lsNEGmbGTX8Dcu4ruuEchsrUjqtNisrnbE5qq7hWm0xYseav5RdokfJhXw2k++qOiKJntwqM5BrE1DQLDdhEEuViiy1Q8dyqnjIfiV41WjIPCm3qtBRvg5J+pHi6aBn0rNHRd8scCZEIX3BecLpkX61LDcX0Q0HTIe4bAccpIg7TjZk2Viln2G2oEfKkaLlXnF2SY2dUdkUrEDql+rGc1j1JGFZHwSEEZEF+dBX73wQPPHQRAhF5yL76qF2A1Ceh9v2ZT/4DcX9MEcZzHxc83zwiDL9/0UKb7cKDQk4kqqtq4E2l99HkTwdZmsjPnFvhh1Rt0dXYuwdEBkx/s9A+1ndgat7a9strOhnKZt8Bf6zWLEHab6opEZfEAn4+y2hotx3UKHeQWGCZ0GeWFQg+BUjL1gq7wGnmCjc+990nL74hk2FCKS65RXR77oY/D3jlWDIRnkC1hy7YH21C1sJH66MyyqbA1aPCOtHfGxQ5/EoIp9bN7sZHwz/VPX7YrGnf8Ams+S3hZJTL0N+YCYR2QLYw8uVZAw48zOb7tmnevpsAxlBHHTKUoYTzv8SpRdK1AhNVgIHmdk3dTsVvbs2MpjUsDKqM8rKqlb77KzQhYYVOpQIQZwDlqUT42UMW4s+wiVFgpwBFUddbKgyyh99lF2eIpW6Oi0Llc+5yCnULs8A=
