---
name: Tests

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          make build

      - name: Run tests
        run: |
          make test-root

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false

  test-pypi:
    name: Upload to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/eodatasets3

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel  # Could also be python -m build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
